version: '3.8'

services:

# docker compose up frontend -d  // --build for new packages
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: yadegar_nextjs_dev
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://yadegar_machine
    command: npm run dev -- -H 0.0.0.0
    networks:
      - shared_net

# docker compose --profile prod up frontend-prod -d --build
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: yadegar_nextjs_prod
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://yadegar_machine
    networks:
      - shared_net
    profiles:
      - prod

networks:
  shared_net:
    external: true
