version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: yadegar_nextjs_dev
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://yadegar_machine
    command: npm run dev -- -H 0.0.0.0
    networks:
      - shared_net

networks:
  shared_net:
    external: true


# --- Production ---
# docker build --target production -t yadegar-next-app .
# docker run -p 3000:3000 -e API_URL=http://yadegar_machine --network shared_net yadegar-next-app
