version: '3.8'

services:

   #  docker-compose up --build
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: yadegar_nextjs_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- -H 0.0.0.0


# docker build --target production -t yadegar-next-app .
# docker run -p 3000:3000 yadegar-next-app

#   frontend_prod:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: production
#     container_name: yadegar_nextjs_prod
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=production
